### ISSUE TITLE
Method to uppercase/lowercase first letter

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/SweetSwift#21]
When getting localized dates, dateStyle: .full sends the day as lowercase in Norwegian. This is fine if it's part of a sentence, but when you use it as the title of a section for example, you want the day to be uppercase.

Apple returns:
`tirsdag 6. desember 2016`

We want:
`Tirsdag 6. desember 2016`

I had to do this in my app.
```swift
let dateString = DateFormatter.localizedString(from: self, dateStyle: .full, timeStyle: .none)
let firstLetter = dateString[0].uppercased()
let range = dateString.startIndex..<dateString.index(after: dateString.startIndex)
let finalDateString = dateString.replacingCharacters(in: range, with: firstLetter)
```

**Comment by elland** [comment]
Why not use `.capitalized`?

**Comment by 3lvis** [comment]
`.capitalized` and `.localizedCapitalized` return:

`Tirsdag 6. Desember 2016` and we don't want the month to be capitalized, just the first letter.

**Comment by designatednerd** [comment]
@3lvis  you still interested in this feature?

**Comment by elland** [comment]
Since this has been revived: I think you can use a `dateFormat` string to achieve that :)

**Comment by elland** [comment]
Actually, you can override the `weekdaySymbols` to return them capitalised 🚀

**Comment by elland** [comment]
Can we close this? :)

**Comment by designatednerd** [comment]
@3lvis if you're still interested in this, please open a PR. I'm gonna close this issue though.
